name: Python Selenium workflow testing
on:
  push:
    branches: 
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Adding steps to run 
    steps:
      - uses: actions/checkout@v4.2.2
      - name: pythonset up 
        uses: actions/setup-python@v4.9.1
      - name: installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute tests
      - run: pytest
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      
      
