name: Python Selenium workflow testing
on:
  push:
    branches: 
      - main
      - june05
  pull_request:
    branches:
      - main
  workflow_dispatch:    
jobs:
  test:
    runs-on: ubuntu-latest
    name: Adding steps to run 
    steps:
      - uses: actions/checkout@v4.2.2
      - name: pythonset up 
        uses: actions/setup-python@v5
      - name: installing dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute tests
        run: pytest Tests/ --html='../TestReport/testreport1.html' -v -s -n 2
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      
      
